var1 = input("Give the numbers to add")
var2 = input()
sum = float(var1)+float(var2)
subs = float(var1)-float(var2)
mult = float(var1)*float(var2)
div = float(var1)/float(var2)
mod = float(var1)%float(var2)
print("sum :{0} \nsubstraction :{1} \n multiplication : {2}\n division : {3}\n modulus : {4}" .format(sum,subs,mult,div,mod))